---
- name: Create configuration for Access Devices
  hosts: access
  connection: local
  gather_facts: no
  pre_tasks:
    - include_vars: "{{ topology_file }}"
  roles:
    - junos-system
    - junos-mclag-common
    - junos-mclag-access
    - build-config
