# System variable used to define temporary directory
# please update tmp_dir variable if needed
tmp_dir: /tmp/build
build_dir: "{{ tmp_dir }}/{{ inventory_hostname }}/tmp"
junos_conf: "config/{{ inventory_hostname }}.conf"

# Global Variables used to generate the common part of the configuration
# these variables are mainly used in the template roles/common/templates/main.conf.j2
# please update these variable and the template as needed to match your environment
global:
    root_hash: $1$ZUlES4dp$OUwWo1g7cLoV/aMWpHUnC/
    login_message: This is the property of Example Corp. Do not login without express permission.
    time_zone: America/Los_Angeles
    name_servers:
    - 8.8.8.8
    - 8.8.4.4
    ntp_servers:
    - 2.2.2.2
    snmp:
        location: "Site 1"
        contact: John Doe
        polling:
        - community: public
    routes:
      static:
        172.16.0.0/12: 10.10.10.10
