mclag_shared:
    mac: 00:11:22:33:33:01

mclag:
  has_l3: false
  links:
    icl:
      links:
        - "{{ topo[inventory_hostname].port3.name }}"
        - "{{ topo[inventory_hostname].port4.name }}"
    mcae:
      to_aggregation:
        key: 1
        links:
          - "{{ topo[inventory_hostname].port1.name }}"
          - "{{ topo[inventory_hostname].port2.name }}"
      server1:
        description: "{{ topo[inventory_hostname].port5.peer }}"
        key: 2
        vlans: ['100-199']
        links:
          - "{{ topo[inventory_hostname].port5.name }}"
