---
# This named task uses the Ansible template module to generate the based part
# of an MC-LAG configuration
- name: Building MC-LAG based devices configuration
  template: >
    src=main.conf.j2
    dest={{ build_dir }}/mclag.base.conf.part
